grails-app/domain/mamespin/Category.groovy
package mamespin

import tools.StringTools

class Category {

    String name
    String description
    String url
    Category parent
    String image

    boolean hidden = false

//    CreditType creditType = CreditType.normal
//    DownloadType type = DownloadType.slow


    static constraints = {
        name()
        description(nullable: true)
        url(nullable: true, url: true, maxSize: 255)
        parent(nullable: true)
        image(nullable: true, maxSize: 255)
    }

    static transients = ['resourcePackCount', 'size', 'humanSize']
    int resourcePackCount = 0
    long size = 0

    String getHumanSize() {
        StringTools.humanReadableString(size)
    }

    static mapping = {
        description(type: 'text')
//        creditType(length: 10)
    }
}

enum CreditType {
    normal, free
}

enum DownloadType {
    slow, fast
}

grails-app/controllers/mamespin/admin/CategoryController.groovy
package mamespin.admin

import mamespin.Category
import mamespin.User

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CategoryController {

    static namespace = "admin"

    static allowedMethods = [save: "POST", update: "POST"]

    def index(Integer max, String search) {
        params.max = Math.min(max ?: 50, 100)
        def list =  Category.createCriteria().list(params) {
            or {
                if (search) {
                    // like("", "%${search.toLowerCase()}%")
                }
            }
        }
        [categoryList: list, category: list.totalCount, search: search]
    }

    def show(Category category) {
        if (category == null) {
            notFound()
            return
        }
        [category:category]
    }

    def create() {
        [category:new Category(params)]
    }

    @Transactional
    def save(Category category) {
        if (category == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (category.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond category.errors, view:'create'
            return
        }

        category.save flush:true

//        flash.message = message(code: 'default.created.message', args: [message(code: 'category.label', default: 'Category'), category.id])
        redirect action: "show", params: [id:category.id]
    }

    def edit(Category category) {
        [category:category]
    }

    @Transactional
    def update(Category category) {
        if (category == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (category.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond category.errors, view:'edit'
            return
        }

        category.save flush:true

//        flash.message = message(code: 'default.updated.message', args: [message(code: 'category.label', default: 'Category'), category.id])
        redirect action: "show", params: [id:category.id]
    }

    @Transactional
    def delete(Category category) {

        if (category == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        category.delete flush:true

//        flash.message = message(code: 'default.deleted.message', args: [message(code: 'category.label', default: 'Category'), category.id])
        redirect action: "index"
    }

    protected void notFound() {
        flash.message = message(code: 'default.not.found.message', args: [message(code: 'category.label', default: 'Category'), params.id])
        redirect action: "index"
    }
}

grails-app/views/category/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <h1><g:message code="default.create.label" args="[entityName]"/></h1>
            <div class="bs-component">
                <ul class="breadcrumb">
                    <li><g:link controller="list">Home</g:link></li>
                    <li><g:link controller="category">category list</g:link></li>
                    <li class="active">Create category</li>
                </ul>
            </div>
        </div>

        <div class="col-lg-12">
            <g:hasErrors bean="${this.category}">
                <div class="container">
                    <div class="row">
                        <div class="bs-component">
                            <div class="alert alert-dismissible alert-danger" style="margin-top:20px">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <ul class="errors" role="alert">
                                    <g:eachError bean="${this.category}" var="error">
                                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                                error="${error}"/></li>
                                    </g:eachError>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </g:hasErrors>
            <div class="row">
                <div class="col-lg-6">
                    <div class="well bs-component">
                        <g:form action="save" class="form-horizontal">
                            <fieldset class="form">
                                <f:all bean="category"/>
                            </fieldset>
                            <fieldset class="buttons">
                                <g:submitButton name="create" class="save"
                                                value="${message(code: 'default.button.create.label', default: 'Create')}"/>
                            </fieldset>
                        </g:form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/category/edit.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <h1><g:message code="default.create.label" args="[entityName]"/></h1>
            <div class="bs-component">
                <ul class="breadcrumb">
                    <li><g:link controller="list">Home</g:link></li>
                    <li><g:link controller="category">category list</g:link></li>
                    <li class="active">Edit category ${category.id}</li>
                </ul>
            </div>
        </div>

        <div class="col-lg-12">
            <g:hasErrors bean="${category}">
                <div class="container">
                    <div class="row">
                        <div class="bs-component">
                            <div class="alert alert-dismissible alert-danger" style="margin-top:20px">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                <ul class="errors" role="alert">
                                    <g:eachError bean="${category}" var="error">
                                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                                                error="${error}"/></li>
                                    </g:eachError>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </g:hasErrors>

            <div class="row">
                <div class="col-lg-6">
                    <div class="well bs-component">
                        <g:form action="update" class="form-horizontal">
                            <g:hiddenField name="id" value="${category?.id}"/>
                            <fieldset class="form">
                                <legend>Edit category ${category?.id}</legend>
                                <f:all bean="${category}"/>
                            </fieldset>

                            <hr/>

                            <div class="form-group">
                                <div class="col-lg-10 col-lg-offset-2">
                                    <input type="submit" class="btn btn-primary"
                                           value="${message(code: 'default.button.update.label', default: 'Create')}"/>
                                </div>
                            </div>
                        </g:form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/category/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main" />
</head>
<body>
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <h1>category</h1>
            <div class="bs-component">
                <ul class="breadcrumb">
                    <li><g:link controller="list">Home</g:link></li>
                    <li class="active">category list</li>
                </ul>
            </div>
        </div>
        <div class="col-lg-12">
            <form class="navbar-form navbar-left">
               <div class="form-group">
                   <input type="text" name="search" class="form-control" placeholder="Buscar" value="${search}">
               </div>
               <button type="submit" class="btn btn-info">Buscar</button>
                <g:link class="btn btn-default" action="create">Crear</g:link>
            </form>
        </div>
        <div class="col-lg-12">
            <div class="bs-component">
            <my:paginate params="[search: search]" max="50" total="${categoryCount ?: 0}" />
            <my:table controllerName="category" collection="${categoryList}" />
            <my:paginate params="[search: search]" max="50" total="${categoryCount ?: 0}" />
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/category/show.gsp
<html>
<head>
    <meta name="layout" content="main" />
    <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
    <title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <div class="bs-component">
                <ul class="breadcrumb">
                    <li><g:link controller="list">Home</g:link></li>
                    <li><g:link controller="category">category list</g:link></li>
                    <li class="active">Show category ${category.id}</li>
                </ul>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset class="buttons">
                    <g:link class="btn btn-default" action="edit" params="[id: category.id]"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <g:link action="delete" class="btn btn-danger" params="[id: category.id]" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">Borrar</g:link>
                </fieldset>
            </div>
            <f:display bean="${category}" />
        </div>
    </div>
</div>
</body>
</html>